sylius_grid:
    grids:
        client_app_user:
            driver:
                name: doctrine/orm
                options:
                    class: Client\Bundle\AppBundle\Entity\AppUser
            sorting:
                lastLogin: desc
            fields:
                username:
                    type: string
                    label: odiseo.ui.username
                    sortable: ~
                email:
                    type: string
                    label: odiseo.ui.email
                    sortable: ~
                lastLogin:
                    type: datetime
                    label: odiseo.ui.last_login
                    sortable: ~
                    options:
                        format: d-m-Y H:i
                enabled:
                    type: twig
                    label: odiseo.ui.enabled
                    sortable: ~
                    options:
                        template: "@OdiseoAdmin/Grid/Field/enabled.html.twig"
            filters:
                search:
                    type: string
                    label: odiseo.ui.search
                    options:
                        fields: [email, username]
                enabled:
                    type: boolean
                    label: odiseo.ui.enabled
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete