liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "media/cache"
    filter_sets:
        square:
            quality: 80
            filters:
                thumbnail: { size: [600, 600], mode: inset }
                background: { size: [600, 600], position: center, color: '#F1F1F1' }