parameters:
    odiseo.security.admin_regex: "^/admin"
    odiseo.security.app_regex: "^/"

security:
    providers:
        admin_provider:
            id: sylius.admin_user_provider.email_or_name_based
        app_provider:
            id: sylius.app_user_provider.email_or_name_based
        oauth:
            id: knpu.oauth2.user_provider

    encoders:
        Sylius\Component\User\Model\UserInterface: sha512

    firewalls:
        admin:
#            switch_user: true
            context: admin
            pattern: "%odiseo.security.admin_regex%"
            form_login:
                provider: admin_provider
                login_path: odiseo_admin_login
                check_path: odiseo_admin_login_check
                failure_path: odiseo_admin_login
                default_target_path: odiseo_admin_index
                use_forward: false
                use_referer: true
            logout:
                path: odiseo_admin_logout
                target: odiseo_admin_login
            anonymous: true
            access_denied_url: odiseo_admin_login

        main:
            context: app
            pattern: "%odiseo.security.app_regex%"
            form_login:
                provider: app_provider
                login_path: app_login
                check_path: app_login_check
                failure_path: app_login
                default_target_path: app_index
            provider: app_provider
            guard:
                authenticators:
                    - "app.security.facebook_authenticator"
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login-check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/css.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin.*, role: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN