vich_uploader:
   db_driver: orm # or mongodb or propel or phpcr
   storage:   gaufrette
   mappings:
        images:
            uri_prefix:         /images
            upload_destination: images_fs
            namer:              vich_uploader.namer_uniqid
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true