odiseo_backend_index:
    path:     /
    defaults: { _controller: "OdiseoAppBundle:Backend/Admin:dashboard" }

odiseo_backend_security:
    resource: "@OdiseoBackendBundle/Resources/config/routing/security.yml"

odiseo_admin_user:
    prefix: /users
    resource: "@OdiseoAppBundle/Resources/config/routing/backend/user.yml"

easy_admin:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /data/
