client_app_index:
    path:     /
    defaults: { _controller: "ClientAppBundle:Main:index" }

client_app_security:
    resource: "@ClientAppBundle/Resources/config/routing/security.yml"

client_app_oauth:
    resource: "@ClientAppBundle/Resources/config/routing/oauth.yml"