client_app_register:
    path: /register
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.app_user:createAction
        _sylius:
            template: "@ClientApp/Register/register.html.twig"
            form: Client\Bundle\AppBundle\Form\Type\AppUserRegistrationType
            event: register
            redirect:
                route: client_app_index

client_app_register_profile:
    path: /register-profile
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.app_user:updateAction
        _sylius:
            template: "@ClientApp/Register/register.html.twig"
            form: Client\Bundle\AppBundle\Form\Type\AppUserRegistrationType
            event: register
            redirect:
                route: client_app_index

client_app_login:
    path: /login
    methods: [GET]
    defaults:
        _controller: sylius.controller.user_security:loginAction
        _sylius:
            template: "@ClientApp/Security/login.html.twig"
            permission: true

client_app_login_check:
    path: /login-check
    methods: [POST]
    defaults:
        _controller: sylius.controller.user_security:checkAction

client_app_logout:
    path: /logout
    methods: [GET]