odiseo_app:
    resource: "@ClientAppBundle/Resources/config/routing/main.yml"
    prefix:   /

odiseo_admin:
    resource: "@ClientAdminBundle/Resources/config/routing/main.yml"
    prefix:   /admin

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"