security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        admin:
            pattern: /admin.*
            form_login:
                provider: fos_userbundle
                login_path: /admin/login
                check_path: /admin/login-check
                default_target_path: /admin
                use_referer: true
            logout:
                path: /admin/logout
                target: /admin/login
            anonymous: true
            context: user
            access_denied_url: /admin/login
            
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                login_path: /login
                check_path: /login_check
            logout:       true
            anonymous:    true
            context: user

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/secure.*, role: ROLE_USER }
        
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login-check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/css.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin.*, role: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN