Odiseo\Bundle\AppBundle\Entity\GaleryImage:
    type: entity
    table: odiseo_galery_image
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            column: name
            type: string
        imageName:
            column: image_name
            type: string
        createdAt:
            type: datetime
            nullable: false
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        preference:
          targetEntity: Odiseo\Bundle\AppBundle\Entity\Preferences
          inversedBy: images
          joinColumn:
            name: preference_id
            referencedColumnName: id
            onDelete: CASCADE