Client\Bundle\AppBundle\Entity\AppUser:
    type: entity
    table: client_app_user
    fields:
        firstName:
            type: string
            nullable: true
        lastName:
            type: string
            nullable: true
