fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Odiseo\Bundle\AppBundle\Entity\User

twig:
    globals:
        locale: '%locale%'

lunetics_locale:
    guessing_order:
        - query
        - router
        - session
        - cookie
        - browser
    allowed_locales:
        - en
        - es
    cookie:
        set_on_change: true

knp_gaufrette:
    stream_wrapper: ~
    adapters:
        image_adapter:
            local:
                directory: %kernel.root_dir%/../web/media/images
                create:    true
    filesystems:
        images_fs:
            adapter:   image_adapter

vich_uploader:
   db_driver: orm # or mongodb or propel or phpcr
   storage:   gaufrette
   mappings:
        images:
            uri_prefix:         /images
            upload_destination: images_fs
            namer:              vich_uploader.namer_uniqid
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

liip_imagine:
    loaders:
        default:
            filesystem:
                data_root: %kernel.root_dir%/../web/media/images
    filter_sets:
        cache: ~
        square:
            filters:
                thumbnail: { size: [550, 550], mode: outbound }

a2lix_translation_form:
    locale_provider: default
    locales: [en, es]
    default_locale: en
    required_locales: [en, es]
    manager_registry: doctrine

sylius_resource:
    resources:
        odiseo.user:
            driver: doctrine/orm
            classes:
                model: Odiseo\Bundle\AppBundle\Entity\User
                repository: Odiseo\Bundle\AppBundle\Repository\UserRepository
                form:
                    default: Odiseo\Bundle\AppBundle\Form\Type\UserType
