App\Entity\AppUser:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [email]
            groups: ['app_user_registration']

    properties:
        email:
            - NotBlank:
                groups: ['odiseo']