services:
    app.form.type.app_user:
        class: App\Form\Type\AppUserRegistrationType
        arguments: ['%sylius.model.app_user.class%', ['app_user_registration']]
        tags:
            - { name: form.type, alias: app_registration }