admin:
    prefix: /admin
    resource: "routes/admin.yaml"

app_security:
    resource: "routes/security.yaml"

app_oauth:
    resource: "routes/oauth.yaml"

app_index:
    path: /
    controller: App\Controller\MainController::index