sylius_user:
    driver: doctrine/orm
    resources:
        app:
            user:
                classes:
                    model: Client\Bundle\AppBundle\Entity\AppUser
                    repository: Client\Bundle\AppBundle\Doctrine\ORM\AppUserRepository
                    interface: Sylius\Component\User\Model\UserInterface
                templates: 'ClientAdminBundle:AppUser'
        oauth:
            user:
                classes:
                    model: Client\Bundle\AppBundle\Entity\AppUserOAuth
                    interface: Sylius\Component\User\Model\UserOAuthInterface
                templates: 'ClientAdminBundle:AppUserOAuth'