parameters:
services:
    client_app.form.type.app_user:
        class: Client\Bundle\AppBundle\Form\Type\AppUserRegistrationType
        arguments: ['%sylius.model.app_user.class%']
        tags:
            - { name: form.type, alias: client_app_registration }