Client\Bundle\AppBundle\Entity\AppUser:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: email
            message: 'Email ya registrado'
            groups: [app_user_registration]
    properties:
        plainPassword:
            - NotBlank:
                message: Tenés que completar el campo Contraseña
                groups: [app_user_registration]
        email:
            - NotBlank:
                message: Tenés que completar el campo Email
                groups: [app_user_registration]