admin_app_user:
    resource: |
        alias: sylius.app_user
        section: admin
        templates: OdiseoAdminBundle:Crud
        except: ['show']
        redirect: index
        grid: app_user
        permission: true
        vars:
            all:
                subheader: "Administra los usuarios"
                templates:
                    form: Admin/AppUser/_form.html.twig
            index:
                icon: user
    type: sylius.resource

sylius_admin_app_user_show:
    path: /app-users/{id}
    methods: [GET]
    defaults:
        _controller: sylius.controller.app_user:showAction
        _sylius:
            section: admin
            permission: true
            template: Admin/AppUser/show.html.twig